version: "3.9"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: capacitacao
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: odyssey
    volumes:
      - odyssey:/var/lib/postgresql

volumes:
  odyssey:
    external: false
